import java.sql.*;
// import java.awt.event.*;
// import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jadepan Thedthong
 */
public class serverGUI extends javax.swing.JFrame {

    /**
     * Creates new form serverGUI
     */
    public serverGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        date = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jButtonBNull1 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jButtonCancelAll = new javax.swing.JButton();
        jButtonNull2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonMoveUp = new javax.swing.JButton();
        jButtonMoveDown = new javax.swing.JButton();
        jButtonIncrease = new javax.swing.JButton();
        jButtonDecrease = new javax.swing.JButton();
        jButtonBNull2 = new javax.swing.JButton();
        jButtonBNull3 = new javax.swing.JButton();
        jButtonBNull41 = new javax.swing.JButton();
        jTextFieldSelectedDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        date.setText("mm/dd/yyyy");
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });

        jButton1.setText("5 Finger Original");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("4 Finger Meal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3 Finger Meal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kid Meal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Gallon of Tea");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Club SW only");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Club SW Meal");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Family Pack");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("SW Meal Combo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Laynes Saurce");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Grill Chess SW");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Grill Chess Meal");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Chicken Finger");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("Crinke Cut Fries");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Potato Salad");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Texas Toast");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("Fountain Drink");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh List");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonBNull1.setText("none");
        jButtonBNull1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBNull1ActionPerformed(evt);
            }
        });

        jButton20.setText("Bottle Drink");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButtonOrder.setText("Order");
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });

        jButtonCancelAll.setText("Cancel All");
        jButtonCancelAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAllActionPerformed(evt);
            }
        });

        jButtonNull2.setText("none");
        jButtonNull2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("CURRENT SELECTION: 501");
        jScrollPane2.setViewportView(jTextArea2);

        jButtonMoveUp.setText("^");
        jButtonMoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveUpActionPerformed(evt);
            }
        });

        jButtonMoveDown.setText("v");
        jButtonMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMoveDownActionPerformed(evt);
            }
        });

        jButtonIncrease.setText("+");
        jButtonIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncreaseActionPerformed(evt);
            }
        });

        jButtonDecrease.setText("-");
        jButtonDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecreaseActionPerformed(evt);
            }
        });

        jButtonBNull2.setText("none");
        jButtonBNull2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBNull2ActionPerformed(evt);
            }
        });

        jButtonBNull3.setText("none");
        jButtonBNull3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBNull3ActionPerformed(evt);
            }
        });

        jButtonBNull41.setText("none");
        jButtonBNull41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBNull41ActionPerformed(evt);
            }
        });

        jTextFieldSelectedDate.setText("Current Date: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(date,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 123,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextFieldSelectedDate,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jButton1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        122,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton2,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        118,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jButton5,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        122,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton8,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        118,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton7,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton6,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jButton9,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        122,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton12,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        118,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton11,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton10,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jButton13,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        122,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton16,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        118,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton15,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jButton14,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        115,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                        false)
                                                                                                .addComponent(
                                                                                                        jButtonBNull3,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(jButton17,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        122,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                jButton20,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                118,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(
                                                                                                                jButtonBNull41,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                115,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        layout.createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        jButtonBNull2,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        118,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(
                                                                                                                        jButtonBNull1,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        115,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                        jButtonRefresh,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        115,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(
                                                                                                        jButtonNull2,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        115,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jButtonIncrease,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButtonMoveUp,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButtonMoveDown,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButtonDecrease,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonOrder,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonCancelAll,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 122,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldSelectedDate, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton3,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton4,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jButton1,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 52,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton2,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton7,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jButton5,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton8,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton11,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton10,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jButton9,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton12,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jButton15,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jButton14,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jButton13,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton16,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonNull2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                .addComponent(jButton17,
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                        layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jButton20,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        52,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jButtonBNull41,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        52,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonRefresh,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBNull1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBNull2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBNull3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonMoveUp)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonMoveDown))
                                                        .addComponent(jButtonCancelAll,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonIncrease)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonDecrease))
                                                        .addComponent(jButtonOrder,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {
        dateString = "";
        dateString = date.getText();

        // check string
        char[] ch = dateString.toCharArray();
        
        if (ch.length != 10) {
            jTextFieldSelectedDate.setText("Wrong Format");
            dateString = "error";
        }
        else if (ch[2] != '/' || ch[5] != '/') {
            jTextFieldSelectedDate.setText("Wrong Format");
            dateString = "error";
        }
        
        String monthStr = String.copyValueOf(ch, 0, 2);
        String dayStr = String.copyValueOf(ch, 3, 2);
        String yearStr = String.copyValueOf(ch, 6, 4);
        
        try{
            int month = Integer.valueOf(monthStr);
            int day = Integer.valueOf(dayStr);
            int year = Integer.valueOf(yearStr);
            
            if (dateString == "error") {
                jTextFieldSelectedDate.setText("Wrong Month Format");
            }
            else if (month > 12 || month < 0) {
                jTextFieldSelectedDate.setText("Wrong Month Format");
                dateString = "error";
            }
            else if (day > 31 || day < 0) {
                jTextFieldSelectedDate.setText("Wrong Date Format");
                dateString = "error";
            }
            else if (year > 2100 || year < 2000) {
                jTextFieldSelectedDate.setText("Year out of range 2000-2100");
            }
            else {
                String output = "Date: " + month + "/" + day + "/" + year;
                jTextFieldSelectedDate.setText(output);
            }
        }
        catch (NumberFormatException ex){
            ex.printStackTrace();
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        // menu number 1 
        int menuIndex = 0;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 4;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 8;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 12;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 16;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 3;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 5;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 6;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 7;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 13;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 14;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 15;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 11;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 10;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 9;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 17;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
            
        Connection conn = null;
        String teamNumber = "12";
        String sectionNumber = "902";
        String dbName = "csce315" + sectionNumber + "_" + teamNumber + "db";
        String dbConnectionString = "jdbc:postgresql://csce-315-db.engr.tamu.edu/" + dbName;
        String userName = "csce315" + sectionNumber + "_" + teamNumber + "user";
        String userPassword = "team12";
        
        String insertCommand = "";
        
        // for testing
        int newPrice = 21;
        int employeeid = 1;
        int locationcode = 123;
        

        try {
            conn = DriverManager.getConnection(dbConnectionString, userName,
            userPassword);
            
            Statement stmtID = conn.createStatement();

            if (dateString != "error" && dateString != "") {
                for (int i = 0; i < menuList.length; i++) {
                    if (menuList[i][1] > 0) {
                        insertCommand = "INSERT INTO customerordertest(menuKey, quantity," +
                        " price, date, employeeid, locationcode) VALUES (";
                        insertCommand += menuList[i][0] + ", "  + menuList[i][1] + ", " 
                            + newPrice + ", '" + dateString + "', " + employeeid + ", "
                            + locationcode + ");";
                        
                        stmtID.executeUpdate(insertCommand);
                    }
                        
                }
                jTextArea2.setText("Updated Order");
                jButtonCancelAllActionPerformed(evt);              
            } 
            else {
                jTextArea1.append("wrong date");
            }
            
        }
        catch (Exception e2)
        {
            e2.printStackTrace();
            System.err.println(e2.getClass().getName()+": "+e2.getMessage());

        }
    }

    private void jButtonCancelAllActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        for (int i = 0; i < menuList.length; i++) {
            menuList[i][1] = 0;
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextArea1.setText(null);
        jTextArea1.append("selected date: " + dateString + "\n");
        for (int i = 0; i < menuList.length; i++) {
            String statement = "menu: " + menuList[i][0] + " | quntity: "
                    + menuList[i][1] + "\n";
            jTextArea1.append(statement);
        }
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 2;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 1;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonMoveUpActionPerformed(java.awt.event.ActionEvent evt) {
        jTextArea2.setText(null);
        if (index > 0) {
            index--;
            jTextArea2.append("Current Menu: " + menuList[index][0]);
        } else {
            jTextArea2.append("out of range");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonIncreaseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (menuList[index][1] < orderlimit) {
            menuList[index][1]++;
        } else {
            jTextArea2.append("\nReached the order limit: " + orderlimit);
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonMoveDownActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextArea2.setText(null);
        if (index < menuList.length - 1) {
            index++;
            jTextArea2.append("Current Menu: " + menuList[index][0]);
        } else {
            jTextArea2.append("out of range");
        }
    }

    private void jButtonDecreaseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (menuList[index][1] > 0) {
            menuList[index][1]--;
        } else {
            jTextArea2.append("\nReached the order limit: 0");
        }
        jButtonRefreshActionPerformed(evt);

    }

    private void jButtonBNull41ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 18;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonNull2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 19;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonBNull3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 20;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonBNull2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 21;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    private void jButtonBNull1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int menuIndex = 22;
        if (menuIndex >= 0 && menuIndex < menuList.length) {
            menuList[menuIndex][1]++;
        } else {
            jTextArea2.append("\nnot a menu yet");
        }
        jButtonRefreshActionPerformed(evt);
    }

    // construct the menu count
    int[][] menuList = { { 501, 0 }, { 502, 0 }, { 503, 0 }, { 504, 0 }, { 505, 0 }, { 506, 0 },
            { 507, 0 }, { 508, 0 }, { 509, 0 }, { 519, 0 }, { 511, 0 }, { 512, 0 }, { 513, 0 },
            { 514, 0 }, { 515, 0 }, { 516, 0 }, { 517, 0 }, { 518, 0 } };

    int firstMenu = menuList[0][0];
    int lastMenu = menuList[menuList.length - 1][0];
    // int selection = menuList[0][0];
    int index = 0;
    int orderlimit = 200;
    String dateString = "";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(serverGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        /*
         * Connection conn = null;
         * String teamNumber = "12";
         * String sectionNumber = "902";
         * String dbName = "csce315" + sectionNumber + "_" + teamNumber + "db";
         * String dbConnectionString = "jdbc:postgresql://csce-315-db.engr.tamu.edu/" +
         * dbName;
         * String userName = "csce315" + sectionNumber + "_" + teamNumber + "user";
         * String userPassword = "team12";
         * 
         * try{
         * conn = DriverManager.getConnection(dbConnectionString, userName,
         * userPassword);
         * }
         * catch (Exception e2)
         * {
         * e2.printStackTrace();
         * System.err.println(e2.getClass().getName()+": "+e2.getMessage());
         * System.exit(0);
         * }
         */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new serverGUI().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JFormattedTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonBNull1;
    private javax.swing.JButton jButtonBNull2;
    private javax.swing.JButton jButtonBNull3;
    private javax.swing.JButton jButtonBNull41;
    private javax.swing.JButton jButtonCancelAll;
    private javax.swing.JButton jButtonDecrease;
    private javax.swing.JButton jButtonIncrease;
    private javax.swing.JButton jButtonMoveDown;
    private javax.swing.JButton jButtonMoveUp;
    private javax.swing.JButton jButtonNull2;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextFieldSelectedDate;
    // End of variables declaration
}
